export const SITE = {
  name: "Terramore",
  slogan: "Cannabis medicinal legal, seguro y acompañado",
  country: "Argentina",
  domain: "https://terramore.com.ar",
  whatsapp: {
    cordoba: "5493516809346",
    baires: "5491166074617",
    argentina: "5493516809346",
  },
  whatsappMessage: "Hola Terramore, quiero más información",
  email: "contacto@terramore.com.ar",
  instagram: "@terramorarg",
  sedes: {
    cordoba: {
      name: "Córdoba",
      address: "Centro Cultural · Córdoba Capital",
      hours: [
        { label: "Lunes a miércoles", time: "10 a 17 hs" },
        { label: "Jueves y viernes", time: "10 a 20 hs" },
      ],
      phone: "+54 9 351 680 9346",
    },
    baires: {
      name: "Buenos Aires",
      address: "Godoy Cruz 3217 · Palermo · Buenos Aires",
      hours: [
        { label: "Lunes a miércoles", time: "11 a 19 hs" },
        { label: "Jueves y viernes", time: "12 a 20 hs" },
      ],
      phone: "+54 9 11 6607 4617",
    },
  },
};

export const products = [
  {
    id: 1,
    slug: "aceite-gotero-10",
    categoria: "ACEITES MEDICINALES",
    nombre: "Aceite con Gotero 10%",
    precio: "$48.000",
    precioEtiqueta: "$$$",
    imagen: "/product1.png",
    galeria: ["/product1.png", "/product2.png", "/product3.png"],
    rating: 5,
    resenas: 128,
    destacado: true,
    resumen:
      "Aceite de cannabis medicinal con 10% de concentración, elaborado con flores analizadas en nuestro laboratorio propio ArMedic. Ideal para una dosificación gradual y equilibrada gracias a su gotero graduado.",
    descripcion: [
      "El Aceite con Gotero 10% es uno de los productos más elegidos por los socios de Terramore. Se elabora a partir de flores de cannabis medicinal cultivadas bajo control y analizadas lote a lote en nuestro laboratorio propio, para garantizar calidad, trazabilidad y constancia en cada presentación.",
      "Su fórmula con 10% de extracto concentrado ofrece un punto de partida equilibrado para quienes buscan una dosificación gradual. Gracias al gotero graduado, podés ajustar la cantidad según tu caso y tu proceso de titulación.",
      "Cada lote está certificado por nuestro laboratorio propio y queda registrado por número de lote. Como todo lo que hacemos, incluye el acompañamiento de nuestro equipo médico y legal durante todo el proceso.",
    ],
    beneficios: [
      { titulo: "Dosificación precisa", desc: "Gotero graduado que te permite medir cada gota con exactitud y constancia." },
      { titulo: "Analizado en laboratorio", desc: "Certificación lote a lote por nuestro laboratorio propio ArMedic." },
      { titulo: "Cultivo supervisado", desc: "Flores de nuestro circuito controlado, sin residuos de riesgo." },
      { titulo: "Trazabilidad transparente", desc: "Conocé el origen, el lote y el análisis de cada presentación." },
    ],
    usos: "Dosis habitual de inicio: entre 2 y 6 gotas, 1 a 2 veces por día, según la indicación de tu médico. Agitar antes de usar y mantener en un lugar seco, fresco y protegido de la luz.",
    composicion: "Extracto concentrado de flores 10% + aceite MCT (grasa de coco fraccionada) 90%.",
    presentacion: "Frasco de 30 ml con gotero graduado.",
    analisis: { cbd: "10%", thc: "< 0,3%", terpenos: "Perfil completo" },
    faq: [
      { q: "¿Necesito receta para comprar este aceite?", a: "Sí. Para acceder a nuestros productos necesitás ser socio de Terramore y contar con tu certificado y habilitación REPROCANN gestionada por nuestros médicos y nuestro equipo legal." },
      { q: "¿Se puede consumir durante el día?", a: "La frecuencia y la dosis dependen de tu caso. El médico te acompaña en la titulación según tus necesidades." },
      { q: "¿Cómo se debe conservar?", a: "Se recomienda guardar el frasco en un lugar fresco, seco y protegido de la luz solar directa." },
    ],
  },
  {
    id: 2,
    slug: "aceite-dispensador-cream",
    categoria: "ACEITES MEDICINALES",
    nombre: "Aceite Dispensador Cream",
    precio: "$52.000",
    precioEtiqueta: "$$$",
    imagen: "/product2.png",
    galeria: ["/product2.png", "/product1.png", "/product3.png"],
    rating: 4.8,
    resenas: 96,
    destacado: true,
    resumen:
      "Aceite medicinal de cannabis en práctico envase dispensador cream, pensado para una aplicación limpia, higiénica y cómoda en el día a día de pacientes REPROCANN.",
    descripcion: [
      "El Aceite Dispensador Cream combina la misma calidad farmacéutica de nuestra línea medicinal con un envase dispensador que facilita la administración diaria, sin pérdidas ni complicaciones. Su contenido es elaborado con flores analizadas en nuestro laboratorio propio ArMedic.",
      "El tapón cream permite dispensar la cantidad exacta de forma higiénica y mantener el producto protegido del aire y de la luz, conservando sus propiedades por más tiempo.",
      "Como todos nuestros productos, forma parte del circuito autorizado de socios con certificación REPROCANN y viene acompañado en todo el proceso por nuestro equipo médico y legal.",
    ],
    beneficios: [
      { titulo: "Envase práctico", desc: "Dispensador cream que facilita la aplicación diaria, sin descuadrar." },
      { titulo: "Fórmula estable", desc: "Protección frente al aire y la luz para mantener su frescura." },
      { titulo: "Mismo estándar de calidad", desc: "Analizado y certificado por el laboratorio propio ArMedic." },
      { titulo: "Para el día a día", desc: "Pensado para pacientes que aplican el aceite todos los días." },
    ],
    usos: "Aplicar según la dosis indicada por tu médico, una o dos veces por día. Agitar suavemente antes de cada uso.",
    composicion: "Extracto de flores 10% + MCT + vitamina E natural.",
    presentacion: "Frasco de 30 ml con dispensador cream.",
    analisis: { cbd: "10%", thc: "< 0,3%", terpenos: "Perfil completo" },
    faq: [
      { q: "¿Envía a todo el país?", a: "Sí, coordinamos la distribución a socios en Córdoba, Buenos Aires y el resto de Argentina." },
      { q: "¿Se puede cambiar la concentración?", a: "Trabajamos con distintas concentraciones según la indicación médica de cada paciente." },
      { q: "¿El producto tiene fecha de vencimiento?", a: "Sí, todos los lotes salen con vencimiento impreso y trazabilidad por lote." },
    ],
  },
  {
    id: 3,
    slug: "flores-gorilla-glue",
    categoria: "FLORES OUTDOOR",
    nombre: "Flores Gorilla Glue",
    precio: "$38.000",
    precioEtiqueta: "$$$",
    imagen: "/product3.png",
    galeria: ["/product3.png", "/product4.png", "/product1.png"],
    rating: 4.9,
    resenas: 241,
    destacado: false,
    resumen:
      "Flores de cannabis medicinal Outdoor con genética Gorilla Glue, cultivadas a sol en nuestro circuito autorizado REPROCANN. Presentadas en frasco hermético de 5 g.",
    descripcion: [
      "Las Flores Gorilla Glue de nuestro circuito exterior son una de las variedades más elegidas de la casa. Su perfil resinoso y su genética popular aportan un complemento valioso dentro del plan terapéutico de cada socio.",
      "Las flores se secan, curan y envasan en nuestro laboratorio propio, preservando aroma, color y resina. Cada lote es analizado y cada frasco se entrega sellado, con vencimiento y número de trazabilidad.",
      "Como toda nuestra referencia, se entrega exclusivamente a socios de Terramore con certificación médica vigente y habilitación REPROCANN gestionada por el equipo legal.",
    ],
    beneficios: [
      { titulo: "Cultivo Outdoor", desc: "Agricultura exterior supervisada, a cielo abierto y con trazabilidad." },
      { titulo: "Curado artesanal", desc: "Curación prolongada que preserva aroma, potencia y textura." },
      { titulo: "Frasco sellado", desc: "Presentación de 5 g certificada y con vencimiento propio." },
      { titulo: "Genética popular", desc: "Gorilla Glue, una variedad reconocida por sus terpenos únicos." },
    ],
    usos: "Uso terapéutico por vaporización o según lo indique tu médico. Cada paciente recibe orientación de su médico en la primera consulta.",
    composicion: "Flor seca entera de alta calidad (5 g).",
    presentacion: "Frasco hermético de 5 g.",
    analisis: { cbd: "Registrado por lote", thc: "Registrado por lote", terpenos: "Resinoso" },
    faq: [
      { q: "¿Con qué otras variedades trabajás?", a: "Contamos con variedades Indoor y Outdoor según disponibilidad anual. Consultá al momento de tu consulta." },
      { q: "¿Cómo preservo mejor las flores?", a: "Guardalas en el frasco original, en un lugar seco y fresco, lejos de la luz directa." },
      { q: "¿Se pueden elegir gramos sueltos?", a: "El despacho se realiza en presentaciones selladas según la indicación recomendada." },
    ],
  },
  {
    id: 4,
    slug: "flores-amnesia-haze",
    categoria: "FLORES INDOOR",
    nombre: "Flores Amnesia Haze",
    precio: "$42.000",
    precioEtiqueta: "$$$",
    imagen: "/product4.png",
    galeria: ["/product4.png", "/product3.png", "/product1.png"],
    rating: 4.9,
    resenas: 175,
    destacado: false,
    resumen:
      "Cultivadas en interior bajo condiciones controladas de luz y humedad, las Flores Amnesia Haze de Terramore ofrecen un perfil versátil y limpio, ideal para planes terapéuticos personalizados.",
    descripcion: [
      "Las Flores Amnesia Haze de cultivo Indoor se producen en espacios totalmente controlados, donde se monitorea la iluminación, la humedad y la temperatura de forma continua. Ese control nos permite obtener flores uniformes, limpias y de muy buena calidad estética.",
      "Después de una curación precisa, se envasan de forma hermética y se analizan por lote en el laboratorio propio, cumpliendo con la trazabilidad que nuestros socios y médicos necesitan.",
      "Son una opción muy elegida dentro de las presentaciones florales seleccionadas por los profesionales para acompañar distintos momentos y estados.",
    ],
    beneficios: [
      { titulo: "Cámara Indoor", desc: "Ambientes controlados de luz, humedad y temperatura." },
      { titulo: "Perfil versátil", desc: "Perfil equilibrado, adaptable a distintos planes terapéuticos." },
      { titulo: "Calidad constante", desc: "Flores homogéneas mantenidas lote a lote." },
      { titulo: "Genética documentada", desc: "Amnesia Haze registrada dentro de nuestro circuito de cultivo." },
    ],
    usos: "Uso vaporizado o por vía inhalatoria según indicación médica. Parte del plan terapéutico supervisado por nuestro equipo.",
    composicion: "Flor seca entera Indoor de calidad premium.",
    presentacion: "Frasco hermético de 10 g.",
    analisis: { cbd: "Registrado por lote", thc: "Registrado por lote", terpenos: "Cítrico" },
    faq: [
      { q: "¿Qué diferencia hay entre flor Indoor y Outdoor?", a: "La Indoor se cultiva en ambientes 100% controlados, logrando condiciones estables y una excelente terminación floral." },
      { q: "¿En qué presentaciones se despachan?", a: "Los despachos se realizan en frascos herméticos sellados de 10 g." },
      { q: "¿Cuándo recibo mi pedido?", a: "Una vez coordinada la compra por WhatsApp, organizamos la entrega en Córdoba, Buenos Aires o envío al interior." },
    ],
  },
  {
    id: 5,
    slug: "crema-antiinflamatoria",
    categoria: "CREMAS MEDICINALES",
    nombre: "Crema Antiinflamatoria",
    precio: "$35.000",
    precioEtiqueta: "$$$",
    imagen: "/product2.png",
    galeria: ["/product2.png", "/product1.png", "/product3.png"],
    rating: 4.7,
    resenas: 89,
    destacado: true,
    resumen:
      "Formulación tópica antiinflamatoria con extracto de cannabis medicinal, para el cuidado de la piel y zonas específicas bajo supervisión del equipo médico de Terramore.",
    descripcion: [
      "Nuestra Crema Antiinflamatoria es una presentación realizada en conjunto con el laboratorio ArMedic. Incorpora extracto de flores analizadas junto con activos calmantes e hidratantes, pensados para brindar confort en zonas musculares y articulares.",
      "Su textura de rápida absorción permite una aplicación práctica en el acompañamiento de molestias localizadas, siempre dentro del plan terapéutico guiado por nuestro equipo médico.",
      "Está disponible para socios que lo requieran en su plan de tratamiento, con la misma trazabilidad y calidad de todo nuestro catálogo.",
    ],
    beneficios: [
      { titulo: "Alivio localizado", desc: "Aplicación tópica pensada para espalda, rodillas u otras zonas específicas." },
      { titulo: "Absorción rápida", desc: "Textura liviana que se absorbe y no deja exceso de grasa." },
      { titulo: "Formulación desarrollada", desc: "Creada junto al laboratorio propio ArMedic." },
      { titulo: "Uso complementario", desc: "Ideal para acompañar el plan terapéutico diario." },
    ],
    usos: "Aplicar 2 a 3 veces por día sobre la zona a tratar, con un suave masaje hasta absorber. Evitar el contacto con mucosas y heridas abiertas.",
    composicion: "Agua, extracto de flores 5%, manteca de karité, vitamina E y activo calmante.",
    presentacion: "Bote de 50 g.",
    analisis: { cbd: "5%", thc: "< 0,1%", terpenos: "Balanceado" },
    faq: [
      { q: "¿La crema es de uso externo?", a: "Sí, es de uso tópico exclusivo. No debe ingerirse." },
      { q: "¿Puedo usarla junto con otros productos?", a: "Consultá siempre con tu médico de cabecera. Cada profesional acompaña el plan." },
      { q: "¿Es apta para pieles sensibles?", a: "La fórmula fue diseñada sobre bases calmantes y recomendamos realizar una prueba previa de aplicación." },
    ],
  },
];

export const getProductBySlug = (slug) => products.find((p) => p.slug === slug) ?? null;

export const getRelatedProducts = (slug, limit = 3) =>
  products.filter((p) => p.slug !== slug).slice(0, limit);